name: TEST BUILD DEPLOY

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Action checkoutâœ…
      uses: actions/checkout@v3
    - name: Setup .NETâ›ï¸
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependenciesğŸªš
      run: dotnet restore
    - name: BuildğŸ—ï¸
      run: dotnet build --no-restore
    - name: TestğŸ› ï¸
      run: dotnet test --no-build --verbosity normal